import test from 'node:test';
import assert from 'node:assert/strict';
import {removeActiveProblem,resolvedProcedures} from '../src/problem-status.js';
const item={id:'d1',nome:'Hipocalemia',titulo:'Hipocalemia leve',campos:{score:2},subitens:[{texto:'Em acompanhamento'}]};
const patient={diagnosticos:['Hipocalemia','Sepse'],diagnostico:'Hipocalemia · Sepse',problemasDiagnosticos:[item,{id:'d2',nome:'Sepse'}],problemasAtivosOrdem:['d1','d2'],metasTerapeuticas:[{id:'p1',problemas:[{id:'d1'}]}]};
test('exclusão sincroniza cadastro preservando outros problemas e planos',()=>{const result=removeActiveProblem(patient,item);assert.deepEqual(result.diagnosticos,['Sepse']);assert.equal(result.diagnostico,'Sepse');assert.deepEqual(result.problemasAtivosOrdem,['d2']);assert.equal(result.problemasDiagnosticos.length,1);assert.deepEqual(result.metasTerapeuticas,patient.metasTerapeuticas);assert.equal(patient.diagnosticos.length,2);});
test('resolução preserva todos os dados e não duplica',()=>{const result=removeActiveProblem(patient,item,{resolved:true,date:'2026-10-04'});assert.deepEqual(result.problemasResolvidos,[{...item,resolvidoEm:'2026-10-04'}]);assert.equal(removeActiveProblem(result,item,{resolved:true}).problemasResolvidos.length,1);assert.deepEqual(JSON.parse(JSON.stringify(result)).problemasResolvidos,result.problemasResolvidos);});
test('problema automático resolvido recebe marcador persistente',()=>{const result=removeActiveProblem(patient,{id:'auto:jejum',automaticoId:'jejum',nome:'Jejum'},{resolved:true});assert.deepEqual(result.problemasAutomaticosEdicoes.jejum,{oculto:true,resolvido:true});assert.equal(result.problemasDiagnosticos.length,2);});
test('procedimentos formatados sem alterar cadastro',()=>{const p={procedimentos:[{id:'p1',nome:'Traqueostomia',data:'2026-10-01'},{nome:''},{nome:'Outro procedimento'}]};assert.deepEqual(resolvedProcedures(p),['Procedimento: Traqueostomia (01/10/2026)','Procedimento: Outro procedimento']);assert.equal(p.procedimentos.length,3);});
